import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import { installHistoryFixture } from './history-fixture.js';
import { mkdir, writeFile } from 'node:fs/promises';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
await page.addInitScript(installHistoryFixture);
const errors = []; page.on('pageerror', e => errors.push(e.message));
try {
    await page.goto('http://localhost:5199');
    await page.locator('.mode-navigation').waitFor();
    await page.locator('.mode-navigation [data-history-game]').click();
    await page.locator('.history-events li').first().waitFor();
    assert.equal(await page.locator('.history-events li').count(), 20);
    const first = await page.locator('.history-events li').first().textContent();
    await page.getByRole('button', { name: '較早紀錄', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.history-actions button')?.disabled === false);
    await page.getByRole('button', { name: '較新紀錄', exact: true }).click();
    await page.waitForTimeout(100);
    assert.equal(await page.locator('.history-events li').first().textContent(), first);
    await page.evaluate(() => { window.__historyFixture.failRead = true; });
    await page.getByRole('button', { name: '重新讀取', exact: true }).click();
    await page.getByRole('alert').waitFor();
    assert.equal(await page.locator('.history-events li').count(), 0);
    await page.evaluate(() => { window.__historyFixture.failRead = false; });
    await page.getByRole('button', { name: '重試', exact: true }).click();
    await page.locator('.history-events li').first().waitFor();
    await page.keyboard.press('Escape');
    await page.locator('.mode-navigation').waitFor();
    await page.waitForFunction(() => document.querySelector('.mode-navigation')?.contains(document.activeElement));
    // Real React handlers through fixture IPC: save failure must preserve input.
    const card = page.locator('.m2-hold').first();
    await card.dispatchEvent('pointerdown', { button: 0 });
    await page.waitForTimeout(3100);
    await page.locator('.m2-note-input').fill('測試：下次再來整理小路');
    await page.evaluate(() => { window.__historyFixture.failHooks = true; });
    await page.locator('.m2-note-confirm').click();
    await page.waitForTimeout(100);
    assert.equal(await page.locator('.m2-note-input').inputValue(), '測試：下次再來整理小路');
    await page.evaluate(() => { window.__historyFixture.failHooks = false; });
    await page.locator('.m2-note-confirm').click();
    await page.locator('.m2-note-input').waitFor({ state: 'detached' });
    assert(await page.evaluate(() => window.__historyFixture.events.some(e => e.payload?.note === '測試：下次再來整理小路')));
    await page.locator('.mode-navigation').getByRole('button', { name: /Rin/ }).click();
    await page.locator('.not-today').click();
    assert(await page.evaluate(() => window.__historyFixture.events.some(e => e.eventType === 'maida.choice.recorded' && e.payload.action === 'not_now')));
    await page.locator('.mode-navigation [data-history-game]').click();
    await page.locator('.history-events li').first().waitFor();
    assert.match(await page.locator('.history-events li').first().textContent(), /NOT NOW/);
    await page.evaluate(() => window.__historyFixture.events.push({ schemaVersion: 2, eventId: 'future', eventType: 'future.event', subject: { namespace: 'steam', id: '413150' }, entity: { displayTitle: {} }, recordedAt: null, payload: {} }));
    await page.getByRole('button', { name: '重新讀取', exact: true }).click();
    await page.waitForTimeout(100);
    const unknown = await page.locator('.history-events li').first().textContent();
    assert.match(unknown, /時間不明/); assert.match(unknown, /來源不明/); assert(!unknown.includes('1970'));
    assert.deepEqual(errors, []);
    await mkdir('design/history-review', { recursive: true });
    await writeFile('design/history-review/interaction.json', JSON.stringify({ passed: true, errors, scope: 'Browser IPC fixture; no real data writes' }, null, 2));
    console.log('History browser interaction checks passed');
} finally { await browser.close(); }
